### ISSUE TITLE
Introduce variation of T, muB and muS across the hypersurface

### ISSUE THREAD

**Issue by doliinychenko** [Duke-QCD/frzout#1]
Fixed T across the hypersurface, and assumption of muB = 0 and muS = 0 limit the applicatility of this code to simulating top RHIC and LHC collisions. For RHIC beam energy scan, NICA, and FAIR one needs a sampler that goes beyond these assumptions.

Of course, there are other samplers, but this code is too beautiful to leave it behind.

**Comment by jbernhard** [comment]
It would be great to remove these restrictions, but that would require a fair amount of work.

I don't consider fixed temperature to be much of an issue, since most particlization is performed on isothermal hypersurfaces.  It's also a pretty fundamental assumption of the sampling algorithm that T is fixed; many thermal quantities are pre-calculated at the given T.  However there is a workaround for variable-T surfaces: Separate the volume elements by their temperature and create multiple `HRG` objects at different temperatures.  This is admittedly unwieldy but it would work.

Adding chemical potentials is possible but probably would require rethinking the momentum sampling algorithm, which uses envelope functions to sample Bose / Fermi distributions.  The relevant code is in function `sample_four_momentum()`.

I am no longer in heavy-ion physics and can't work on this, but am happy to accept pull requests.
